project:
  type: website
  output-dir: docs

website:
  title: "Harika Mandava"
  site-url: https://github.com/hmandava-wq
  #google-analytics: # something to come here

  navbar:
    logo: headshots/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lab Notebook"
        href: notebook.qmd
      - text: "Lab Handbook"
        href: https://alcalalab.github.io/resources/
    right:
      - icon: github
        href: https://github.com/hmandava-wq
  
  page-footer:
    left: |
      © 2026 Your Name

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    link-external-icon: false

execute:
  freeze: auto



